# 2-1 张量数据结构
Pytorch的基本数据结构是张量Tensor。张量即多维数组。Pytorch的张量和numpy中的array很类似。

本节我们主要介绍张量的数据类型、张量的维度、张量的尺寸、张量和numpy数组等基本概念。

## 一、张量的数据类型
张量的数据类型和numpy.array基本一一, 但是不支持**str**类型。
包括:
* torch.float64(torch.double)
* **torch.float32(torch.float)**
* torch.float16
* torch.int64(torch.long)
* torch.int32(torch.int)
* torch.int16
* torch.int8
* torch.unit8
* torch.bool
一般神经网络模型使用的都是torch.float32类型


In [1]:
import numpy as np
import torch

In [2]:
# 自动推断数据类型

i = torch.tensor(1)
print(i, i.dtype)
x = torch.tensor(2.0)
print(x, x.dtype)
b = torch.tensor(True)
print(b, b.dtype)

tensor(1) torch.int64
tensor(2.) torch.float32
tensor(True) torch.bool


In [13]:
# 指定数据类型
i = torch.tensor([1], dtype=torch.int32)
print(i, i.dtype)
x = torch.tensor(2.0, dtype=torch.double)
print(x, x.dtype)

tensor([1], dtype=torch.int32) torch.int32
tensor(2., dtype=torch.float64) torch.float64


In [14]:
i_v = i.detach()
i_v

tensor([1], dtype=torch.int32)

In [15]:
i[0] = 2

In [16]:
i_v  # share the same memory with the origin

tensor([2], dtype=torch.int32)

In [12]:
# 使用特定类型构造函数
i = torch.IntTensor([3])  # 不输入list的话, 就是随机出指定个数的tensor
print(i, i.dtype)
x = torch.FloatTensor([2])
print(x, x.dtype)
b = torch.BoolTensor([1, 2, 0])
print(b, b.dtype)

tensor([3], dtype=torch.int32) torch.int32
tensor([2.]) torch.float32
tensor([ True,  True, False]) torch.bool


In [19]:
# 不同类型转换
i = torch.tensor([1])
x = i.float()
i = x.type(torch.float32)
print(x)
print(i)
z = i.type_as(b)
print(z)

tensor([1.])
tensor([1.])
tensor([True])


## 二、张量的维度
不同类型的数据可以用不同维度的张量来表示

标量为0维张量, 向量为1维张量, 矩阵为2维张量。

彩色图像有rgb三个通道, 可以表示为3维张量。

视频还有时间维度, 可以表示为4维张量。

In [21]:
scalar = torch.tensor(2)
print(scalar)
print(scalar.dim())  # 标量, 0维张量

tensor(2)
0


In [25]:
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])  # 向量, 1维张量
print(vector)
print(vector.dim())

tensor([1., 2., 3., 4.])
1


In [26]:
matrix = torch.tensor([[1.0, 2.0], [2.0, 4.0]])
print(matrix)
print(matrix.dim())

tensor([[1., 2.],
        [2., 4.]])
2


In [28]:
tensor3 = torch.tensor([[[1., 2.]], [[3., 4.]], [[5., 5.]]])
print(tensor3)
print(tensor3.dim())

tensor([[[1., 2.]],

        [[3., 4.]],

        [[5., 5.]]])
3


In [29]:
tensor4 = torch.tensor([[[[1.0,1.0],[2.0,2.0]],[[3.0,3.0],[4.0,4.0]]],
                        [[[5.0,5.0],[6.0,6.0]],[[7.0,7.0],[8.0,8.0]]]])  # 4维张量
print(tensor4)
print(tensor4.dim())

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]]],


        [[[5., 5.],
          [6., 6.]],

         [[7., 7.],
          [8., 8.]]]])
4


## 三、张量的尺寸
可以使用shape属性或者size方法查看张量在每一维度的长度

可以使用view方法改变张量尺寸

如果view方法改变尺寸失败, 可以使用reshape方法

In [31]:
scalar = torch.tensor([True])
print(scalar.size())
print(scalar.shape)

torch.Size([1])
torch.Size([1])


In [32]:
vector = torch.tensor([1.0,2.0,3.0,4.0])
print(vector.size())
print(vector.shape)

torch.Size([4])
torch.Size([4])


In [35]:
# 使用view可以改变张量尺寸
vector = torch.arange(0, 12)
print(vector)
print(vector.shape)

matrix34 = vector.view(3, 4)
print(matrix34)
print(matrix34.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [36]:
v_r = vector.reshape([3, 4])
v_r

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [37]:
print(id(vector) == id(matrix34), id(vector) == id(v_r), id(matrix34) == id(v_r))  # 这个变量其实只是指向了记录tensor的形状(size)、步长(stride)、数据类型(type)等信息的内存区域

False False False


In [39]:
print(id(vector.storage()) == id(v_r.storage()), id(vector.storage()) == id(matrix34.storage()), id(matrix34.storage()) == id(v_r.storage()))  # 这三个的储存一样

True True True


In [62]:
# 有些操作会让张量储存结构扭曲, 直接使用view会失败, 可以使用reshape方法

matrix26 = torch.arange(0, 12).view(2, 6)
print(matrix26)
print(matrix26.shape)
# 转置操作让张量储存结构扭曲
matrix62 = matrix26.t()
print(id(matrix26.storage()) == id(matrix62.storage()))
print(matrix62.is_contiguous())

# 直接使用view会导致方法失败
matrix34 = matrix62.view(3, 4)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
True
False


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [63]:
matrix34 = matrix62.reshape([3, 4])
print(matrix34.is_contiguous())

True


In [64]:
print(id(matrix34.storage()) == id(matrix62.storage()))
print(id(matrix34.storage()) == id(matrix26.storage()))

True
True


In [65]:
matrix34_c = matrix34.clone()
matrix34_c[0, 0] = 100
matrix34  # matrix34不会改变

tensor([[ 0,  6,  1,  7],
        [ 2,  8,  3,  9],
        [ 4, 10,  5, 11]])

In [66]:
matrix34_v = matrix34.view(3, 4)

In [67]:
matrix34_v[0, 0] = 100  # view会改变原来的值
matrix34

tensor([[100,   6,   1,   7],
        [  2,   8,   3,   9],
        [  4,  10,   5,  11]])

In [68]:
matrix34_r = matrix34.reshape([3, 4])
matrix34_r[0, 0] = 110
matrix34  # 这时的reshape返回的是view

tensor([[110,   6,   1,   7],
        [  2,   8,   3,   9],
        [  4,  10,   5,  11]])

In [69]:
print(id(matrix34_c.storage()) == id(matrix34.storage()))
print(id(matrix34_v.storage()) == id(matrix34.storage()))
print(id(matrix34_r.storage()) == id(matrix34.storage()))
# 三个使用的储存器又是一样的

True
True
True


In [79]:
print(id(matrix34.storage()))
print(id(matrix34_v.storage()))
print(id(matrix34_r.storage()))
print(id(matrix34_c.storage()))

139996598936520
139996598937096
139996598937864
139996598937544


In [81]:
print(matrix34.storage() is matrix34_v.storage())

False


## 四、张量和numpy数组
可以使用numpy方法从Tensor得到numpy数组, 也可以用torch.from_numpy从numpy数组中得到Tensor

这两种方法关联的Tensor和numpy数组是共享数据内存的

如果改变其中一个, 另一个的值也会发生改变。

如果有需要, 可以使用张量的clone方法拷贝张量, 中断这种关联。

此外, 还可以使用item方法从标量张量得到对应的Python数值。

使用tolist方法获得对于的Python数值列表。

In [88]:
# torch.from_numpy函数从numpy数组
arr = np.zeros(3)
tensor = torch.from_numpy(arr)
print("before add 1:")
print(arr)
print(tensor)

print("\n after add 1:")
# np.add(arr, 1, out = arr)
arr += 1
print(arr)
print(tensor)

before add 1:
[0. 0. 0.]
tensor([0., 0., 0.], dtype=torch.float64)

 after add 1:
[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


In [89]:
# 可以用clone() 方法拷贝张量，中断这种关联

tensor = torch.zeros(3)

#使用clone方法拷贝张量, 拷贝后的张量和原始张量内存独立
arr = tensor.clone().numpy() # 也可以使用tensor.data.numpy()
print("before add 1:")
print(tensor)
print(arr)

print("\nafter add 1:")

#使用 带下划线的方法表示计算结果会返回给调用 张量
tensor += 1
print(tensor)
print(arr)

before add 1:
tensor([0., 0., 0.])
[0. 0. 0.]

after add 1:
tensor([1., 1., 1.])
[0. 0. 0.]


In [92]:
# item方法和tolist方法可以将张量转换成Python数值和数值列表
scalar = torch.tensor(1.0)
s = scalar.item()
print(s)
print(type(s))
s += 1
print(scalar)
tensor = torch.rand(2,2)
t = tensor.tolist()
print(t)
print(type(t))
t[0] = 100
print(tensor)

1.0
<class 'float'>
tensor(1.)
[[0.2645394802093506, 0.6845030188560486], [0.711341917514801, 0.8271015286445618]]
<class 'list'>
tensor([[0.2645, 0.6845],
        [0.7113, 0.8271]])
