# 4-2 张量的数学运算
张量的操作主要包括张量的结构操作和数学运算。

数学运算主要有：
* 标量运算
* 向量运算
* 矩阵运算
* 广播机制

## 一、标量运算

In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([[1., 2], [-3, 4]])
b = torch.tensor([[5., 6], [7, 8]])
a + b  # 运算符重载

tensor([[ 6.,  8.],
        [ 4., 12.]])

In [3]:
a-b

tensor([[ -4.,  -4.],
        [-10.,  -4.]])

In [4]:
a*b

tensor([[  5.,  12.],
        [-21.,  32.]])

In [5]:
a/b

tensor([[ 0.2000,  0.3333],
        [-0.4286,  0.5000]])

In [6]:
a**2

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [7]:
a**(0.5)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [8]:
a%3

tensor([[1., 2.],
        [-0., 1.]])

In [9]:
a // 3

tensor([[ 0.,  0.],
        [-1.,  1.]])

In [10]:
a >= 2

tensor([[False,  True],
        [False,  True]])

In [11]:
(a>=2) & (a<=3)

tensor([[False,  True],
        [False, False]])

In [12]:
(a>=2) and (a<=3)   # 直接用and不能处理多布尔

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [13]:
(a >= 2) | (a<=3)

tensor([[True, True],
        [True, True]])

In [14]:
a == 5

tensor([[False, False],
        [False, False]])

In [15]:
torch.sqrt(a)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [16]:
a = torch.tensor([1.0,8.0])
b = torch.tensor([5.0,6.0])
c = torch.tensor([6.0,7.0])

d = a+b+c
print(d)

tensor([12., 21.])


In [17]:
print(torch.max(a,b))

tensor([5., 8.])


In [18]:
print(torch.min(a,b))

tensor([1., 6.])


In [19]:
x = torch.tensor([2.6,-2.7])

# 注意, 这里的结果其实还是float
print(torch.round(x)) #保留整数部分，四舍五入
print(torch.floor(x)) #保留整数部分，向下归整
print(torch.ceil(x))  #保留整数部分，向上归整
print(torch.trunc(x)) #保留整数部分，向0归整

tensor([ 3., -3.])
tensor([ 2., -3.])
tensor([ 3., -2.])
tensor([ 2., -2.])


In [20]:
x = torch.tensor([2.6,-2.7])
print(torch.fmod(x, 2)) #作除法取余数 
print(torch.remainder(x, 2)) #作除法取剩余的部分，结果恒正

tensor([ 0.6000, -0.7000])
tensor([0.6000, 1.3000])


In [21]:
# 幅值裁剪
x = torch.tensor([0.9,-0.8,100.0,-20.0,0.7])
y = torch.clamp(x,min=-1,max = 1)
z = torch.clamp(x,max = 1)
print(y)
print(z)

tensor([ 0.9000, -0.8000,  1.0000, -1.0000,  0.7000])
tensor([  0.9000,  -0.8000,   1.0000, -20.0000,   0.7000])


## 二、向量运算
向量运算符只在特定轴上运算, 将一个向量映射到一个标量或者另一个向量

In [22]:
# 统计值
a = torch.arange(1, 10).float()
print(torch.sum(a))
print(torch.mean(a))
print(torch.max(a))
print(torch.min(a))
print(torch.prod(a))  # 累乘
print(torch.var(a))  # 方差
print(torch.std(a))  # 标准差
print(torch.median(a))  # 中位数

tensor(45.)
tensor(5.)
tensor(9.)
tensor(1.)
tensor(362880.)
tensor(7.5000)
tensor(2.7386)
tensor(5.)


In [25]:
# 指定维度计算统计值
b = a.view(3, 3)
print(b)
print(torch.max(b, dim=0))  # 按dim=0遍历找到最大的, 也就是列最大
print(torch.max(b, dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))


In [27]:
c = torch.arange(1, 28)
c_ = c.view(3, 3, 3)
print(c_)
print(torch.max(c_, dim=0))
print("===================")
print(torch.max(c_, dim=1))
print("===================")
print(torch.max(c_, dim=2))

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])
torch.return_types.max(
values=tensor([[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))
torch.return_types.max(
values=tensor([[ 7,  8,  9],
        [16, 17, 18],
        [25, 26, 27]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))
torch.return_types.max(
values=tensor([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))


In [29]:
c_[2,...]

tensor([[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]])

In [30]:
# cum扫描
a = torch.arange(1, 10)
print(torch.cumsum(a, 0))
print(torch.cumprod(a, 0))
print(torch.cummax(a, 0).values)
print(torch.cummax(a, 0).indices)
print(torch.cummin(a, 0))

tensor([ 1,  3,  6, 10, 15, 21, 28, 36, 45])
tensor([     1,      2,      6,     24,    120,    720,   5040,  40320, 362880])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.return_types.cummin(
values=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1]),
indices=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]))


In [32]:
# torch.sort和torch.topk可以对张量排序
a = torch.tensor([[9, 8, 7], [1, 3, 2], [5, 6, 4]]).float()
print(torch.topk(a, 2, dim=0), "\n")
print(torch.topk(a, 2, dim=1), "\n")
print(torch.sort(a, dim=1), "\n")

# 利用topk就可以实现Pytorch的KNN算法

torch.return_types.topk(
values=tensor([[9., 8., 7.],
        [5., 6., 4.]]),
indices=tensor([[0, 0, 0],
        [2, 2, 2]])) 

torch.return_types.topk(
values=tensor([[9., 8.],
        [3., 2.],
        [6., 5.]]),
indices=tensor([[0, 1],
        [1, 2],
        [1, 0]])) 

torch.return_types.sort(
values=tensor([[7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.]]),
indices=tensor([[2, 1, 0],
        [0, 2, 1],
        [2, 0, 1]])) 



## 三、矩阵运算
矩阵运算包括: 矩阵乘法、转置、逆矩阵、矩阵范数、行列式、特征值、矩阵分解

In [33]:
# 矩阵乘法
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[2, 0], [0, 2]])
print(a @ b)

tensor([[2, 4],
        [6, 8]])


In [34]:
# 矩阵转置
a = torch.tensor([[1.0, 2], [3, 4]])
print(a.t())

tensor([[1., 3.],
        [2., 4.]])


In [35]:
# 矩阵逆, 必须为浮点类型
a = torch.tensor([[1., 2], [3, 4]])
print(torch.inverse(a))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [36]:
# 矩阵求trace
a = torch.tensor([[1., 2], [3, 4]])
print(torch.trace(a))

tensor(5.)


In [37]:
# 矩阵范数
a = torch.tensor([[1., 2], [3, 4]])
print(torch.norm(a))

tensor(5.4772)


In [38]:
# 矩阵行列式
a = torch.tensor([[1., 2], [3, 4]])
print(torch.det(a))

tensor(-2.0000)


In [39]:
# 矩阵特征值和特征向量
a = torch.tensor([[1., 2], [-5, 4]], dtype=torch.float)
print(torch.eig(a, eigenvectors=True))

torch.return_types.eig(
eigenvalues=tensor([[ 2.5000,  2.7839],
        [ 2.5000, -2.7839]]),
eigenvectors=tensor([[ 0.2535, -0.4706],
        [ 0.8452,  0.0000]]))


In [40]:
# 矩阵QR分解, 将一个方阵分解为一个正交矩阵q和一个上三角矩阵r
a = torch.tensor([[1., 2], [3, 4]])
q, r = torch.qr(a)
print(q, "\n")
print(r, "\n")
print(q@r)

tensor([[-0.3162, -0.9487],
        [-0.9487,  0.3162]]) 

tensor([[-3.1623, -4.4272],
        [ 0.0000, -0.6325]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000]])


In [41]:
#矩阵svd分解
#svd分解可以将任意一个矩阵分解为一个正交矩阵u,一个对角阵s和一个正交矩阵v.t()的乘积
#svd常用于矩阵压缩和降维
a=torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])

u,s,v = torch.svd(a)

print(u,"\n")
print(s,"\n")
print(v,"\n")

print(u@torch.diag(s)@v.t())

tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]]) 

tensor([9.5255, 0.5143]) 

tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])


## 四、广播机制
Pytorch的广播规则和numpy是一样的:

1. 如果张量的维度不同, 将维度较小的张量进行扩展, 知道两个张量维度一样

2. 如果两个张量在某个维度长度一样, 或者其中一个张量在该维度的长度为1, 那么我们就说这两个张量在该维度上是相容的

3. 如果两个张量在所有维度上都是相容的, 它们就能使用广播

4. 广播之后, 每个维度的长度将取两个张量在该维度长度的较大值

5. 在任何一个维度上, 如果一个张量的长度为1, 另一个张量的长度大于1, 那么该维度上就好像是对第一个张量进行了复制

In [42]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
print(b + a)

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])


In [43]:
a_broad,b_broad = torch.broadcast_tensors(a,b)
print(a_broad,"\n")
print(b_broad,"\n")
print(a_broad + b_broad) 

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]) 

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]) 

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])
