# 2-1 张量数据结构

TensorFlow之中, 计算图**节点**就是**数学运算**而连接**节点**的边就是 **张量**

**TensorFlow程序 = 张量数据结构 + 计算图算法语言**

从行为特性上来看, 一般有两种常用的张量:
* 常量constant, 不可以在计算图中被重新赋值
* 变量Variable, 可以在计算图中用assign等算子重新赋值

## 一 常量张量

In [9]:
import numpy as np
import tensorflow as tf

i = tf.constant(1)  # 默认类型是tf.int32
l = tf.constant(1, dtype = tf.int64)
f = tf.constant(1.23)  # 默认类型tf.float32
d = tf.constant(3.14, dtype = tf.double)
s = tf.constant("hello world")  # tf.string类型
b = tf.constant(True)  # tf.bool类型

print(tf.int64 == np.int64)
print(tf.bool == np.bool)
print(tf.double == np.float64)
print(tf.string == np.unicode)
print(tf.float64 == np.float64)
print(tf.float64 == tf.double)
print(tf.string == np.string_)
print(tf.string == np.str_)
print(np.string_ == np.str_) # np.str_就是Python内置模块的str, string_是numpy自己的数据结构

True
True
True
False
True
True
True
True
False


### 张量维度问题
简单总结一下张量的维度就是：有几层中括号就是多少维的张量

In [17]:
scalar = tf.constant(True)  # 标量就是0维的
vector = tf.constant([1.1, 2.0, 3.0, 4.0])  # 向量是1维的
matrix = tf.constant([[1, 2], [3, 4]])  # 矩阵是2维的
print(tf.rank(vector))
print(vector.shape)
print(np.ndim(vector))
print(np.ndim(vector.numpy()))

tf.Tensor(1, shape=(), dtype=int32)
(4,)
1
1


### 张量类型改变
可以使用tf.cast改变张量数据类型：但是不能直接把字符串改成数值类型

In [20]:
h = tf.constant([123, 456])
f = tf.cast(h, dtype = tf.float32)
print(h)
print(f)

tf.Tensor([123 456], shape=(2,), dtype=int32)
tf.Tensor([123. 456.], shape=(2,), dtype=float32)


In [30]:
u = tf.constant("你好")
print(u.numpy())
print(u)
print(u.numpy().decode())
print(tf.strings.unicode_decode(u, "utf8"))  # 解析为unicode的index

b'\xe4\xbd\xa0\xe5\xa5\xbd'
tf.Tensor(b'\xe4\xbd\xa0\xe5\xa5\xbd', shape=(), dtype=string)
你好
tf.Tensor([20320 22909], shape=(2,), dtype=int32)


In [31]:
# 把字符串解析为数字
s = tf.constant(["111", "222"], dtype = tf.string)
num = tf.strings.to_number(s)  # 解析后默认float32
print(num)

tf.Tensor([111. 222.], shape=(2,), dtype=float32)


## 二 变量张量
模型中需要被训练的参数一般被设置为变量

In [36]:
# 常量值不可以被改变, 常量的重新赋值相当于创造新的内存空间
c = tf.constant([1.0, 2.0])
print(c)
print(id(c))
c = c + tf.constant([1, 2], dtype = tf.float32)
print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
139643427544928
tf.Tensor([2. 4.], shape=(2,), dtype=float32)
139643427541400


In [41]:
# 变量可以改变, 通过assign, assign_add等方法改变
v = tf.Variable([1.0, 2.0], name = "v")
print(v)
print(id(v))

v.assign_add([1.0, 1.0])
print(v)
print(id(v))

v = v + tf.Variable([1.0, 1.0])  # 这样直接加就会改变地址
print(v)
print(id(v))

<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
139643453071488
<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
139643453071488
tf.Tensor([3. 4.], shape=(2,), dtype=float32)
139643549758184
