# 4-1 张量的结构操作
张量的操作主要分为：
* 张量的结构操作：张量创建、索引切片、维度变换、合并分割
* 张量的数学运算: 标量运算、向量运算、矩阵运算、广播机制

In [1]:
import tensorflow as tf
import numpy as np

## 1. 创建张量

In [2]:
a = tf.constant([1, 2, 3], dtype = tf.float32)
tf.print(a)

[1 2 3]


In [3]:
b = tf.range(1, 10, delta = 2)
tf.print(b)

[1 3 5 7 9]


In [6]:
c = tf.linspace(0.0, 2*3, 100)
tf.print(c)
print(c)

[0 0.0606060624 0.121212125 ... 5.87878799 5.939394 6]
tf.Tensor(
[0.         0.06060606 0.12121212 0.18181819 0.24242425 0.3030303
 0.36363637 0.42424244 0.4848485  0.54545456 0.6060606  0.6666667
 0.72727275 0.7878788  0.8484849  0.90909094 0.969697   1.030303
 1.0909091  1.1515152  1.2121212  1.2727273  1.3333334  1.3939395
 1.4545455  1.5151515  1.5757576  1.6363637  1.6969697  1.7575758
 1.8181819  1.878788   1.939394   2.         2.060606   2.1212122
 2.1818182  2.2424242  2.3030305  2.3636365  2.4242425  2.4848485
 2.5454545  2.6060607  2.6666667  2.7272727  2.787879   2.848485
 2.909091   2.969697   3.030303   3.0909092  3.1515152  3.2121212
 3.2727275  3.3333335  3.3939395  3.4545455  3.5151515  3.5757577
 3.6363637  3.6969697  3.757576   3.818182   3.878788   3.939394
 4.         4.060606   4.121212   4.1818185  4.2424245  4.3030305
 4.3636365  4.4242425  4.4848485  4.5454545  4.606061   4.666667
 4.727273   4.787879   4.848485   4.909091   4.969697   5.030303
 5.090909   5.1

In [7]:
d = tf.zeros([3, 3])
print(d)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [8]:
a = tf.ones([3, 3])
b = tf.zeros_like(a, dtype = tf.float32)
print(b)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [10]:
b = tf.fill([3, 2], 5)
print(b)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [11]:
help(tf.fill)

Help on function fill in module tensorflow.python.ops.array_ops:

fill(dims, value, name=None)
    Creates a tensor filled with a scalar value.
    
    This operation creates a tensor of shape `dims` and fills it with `value`.
    
    For example:
    
    >>> tf.fill([2, 3], 9)
    <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
    array([[9, 9, 9],
           [9, 9, 9]], dtype=int32)>
    
    `tf.fill` evaluates at graph runtime and supports dynamic shapes based on
    other runtime `tf.Tensors`, unlike `tf.constant(value, shape=dims)`, which
    embeds the value as a `Const` node.
    
    Args:
      dims: A 1-D sequence of non-negative numbers. Represents the shape of the
        output `tf.Tensor`. Entries should be of type: `int32`, `int64`.
      value: A value to fill the returned `tf.Tensor`.
      name: Optional string. The name of the output `tf.Tensor`.
    
    Returns:
      A `tf.Tensor` with shape `dims` and the same dtype as `value`.
    
    Raises:
      InvalidAr

In [13]:
# 均匀随机分布
a = tf.random.uniform([5], minval = -5, maxval = 5)
print(a)

tf.Tensor([4.5562916 4.586997  3.4834461 4.6098537 3.542819 ], shape=(5,), dtype=float32)


In [15]:
# 正态分布
b = tf.random.normal([3, 3], mean = 0.0, stddev = 1.0)
print(b)

tf.Tensor(
[[-1.0012541   1.4263123   0.03094142]
 [ 1.0659183   1.018811   -1.4684073 ]
 [ 0.34250325 -0.44787502  0.7764029 ]], shape=(3, 3), dtype=float32)


In [16]:
# 正态分布, 剔除2倍标准差之外的数据
c = tf.random.truncated_normal([5, 5], mean = 0, stddev = 1, dtype = tf.float32)
print(c)

tf.Tensor(
[[-0.8885505   1.9866174  -0.9893501   1.157576   -1.542481  ]
 [ 1.1783073  -1.3005294  -1.15169     1.0989115  -0.6353092 ]
 [-0.28226504 -1.1738544  -0.61954844  0.17495376 -0.2519497 ]
 [-0.7041106   0.68609506 -1.2576078  -0.03894141  0.04698461]
 [-0.6698293  -1.1513939   1.0306796   1.1181413  -0.47335675]], shape=(5, 5), dtype=float32)


In [18]:
# 特殊矩阵
I = tf.eye(3, 3)
print(I)
t = tf.linalg.diag([1, 2, 3])
print(t)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), dtype=int32)


## 2 索引切片

张量的索引切片方式和numpy几乎是一样的。切片支持缺省参数和省略号。

对于tf.Variable，可以通过索引和切片对部分元素进行修改。

对于提取张量的连续子区域，也可以使用tf.slice。

此外，对于不规则的切片提取，可以使用tf.gather, tf.gather_nd, tf.boolean_mask

其中tf.boolean_mask的功能最为强大, 可以实现其余两者的功能。

如果要通过修改张量的某些元素得到新的张量，可以使用tf.where和tf.scatter_nd

In [19]:
t = tf.random.uniform([5, 5], minval = -5, maxval = 5, dtype = tf.int32)
print(t)

tf.Tensor(
[[-5  4 -5 -5 -4]
 [-5  0 -5  0  3]
 [-4 -5 -1 -3 -4]
 [-1 -1  0 -3 -1]
 [-4 -5 -3 -2  3]], shape=(5, 5), dtype=int32)


In [22]:
# 第一行
print(t[0])

tf.Tensor([-5  4 -5 -5 -4], shape=(5,), dtype=int32)


In [23]:
# 最后一行
print(t[-1])

tf.Tensor([-4 -5 -3 -2  3], shape=(5,), dtype=int32)


In [25]:
# 第一行第三列
print(t[0, 2])

tf.Tensor(-5, shape=(), dtype=int32)


In [27]:
# 第1至3行
print(t[0:3, :])

tf.Tensor(
[[-5  4 -5 -5 -4]
 [-5  0 -5  0  3]
 [-4 -5 -1 -3 -4]], shape=(3, 5), dtype=int32)


In [28]:
# 第1行到最后一行, 第1列到最后一列每隔2列取一次
print(t[:, ::2])

tf.Tensor(
[[-5 -5 -4]
 [-5 -5  3]
 [-4 -1 -4]
 [-1  0 -1]
 [-4 -3  3]], shape=(5, 3), dtype=int32)


以上的切片方式相对规则, 如果需要对不规则的切片提取就需要用到tf.gather, tf.gather_nd, tf.boolean_mask

例子: 有4个班级, 每个班级10个学生, 每个学生7门科目, 用一个三维张量去表示

In [33]:
scores = tf.random.uniform([4, 10, 7], minval = 0, maxval = 100, dtype = tf.int32)
print(scores)

tf.Tensor(
[[[11 94 64 27 72  9 87]
  [56 48 44 63 78  9 86]
  [85 13 23 20 21 28 53]
  [77 50 93 47 46 96 26]
  [10 27 96 76 24 49 75]
  [35 75  2 72 81 14 46]
  [91  3 68 87 68 83 22]
  [11 43 90 28 55 43 52]
  [14  3  5 85 17 13 27]
  [23 20 19 64 94 62 15]]

 [[95 63 47 19 12 70 53]
  [ 4 76 45 57 49 49 25]
  [91 67 97 36 15 62 44]
  [58 15 30 59  3 79 11]
  [80 22  2 33 73  1 65]
  [24 39 17 53 23 76 67]
  [29 94  3 14 48 16 99]
  [23 25 34 20 30 95 97]
  [12 93 81 77 12 57 12]
  [68 11 86 61 73 62 75]]

 [[12 97 42 95 35 54 52]
  [79 71 12 61 99 57 60]
  [20  1 15 16 44 75 66]
  [78 35 35 80 30 18 37]
  [57 11  8 72 67 68 45]
  [77 46 17 63 98 67 37]
  [21 13 95 83 71 15 74]
  [21 88 62 95 41  7 37]
  [93 71 95 14  2 85 77]
  [99  9 57 50 93 34 10]]

 [[61 53 30 10 29 30 93]
  [ 0 25 39 27  6 67 64]
  [31 59 40 66 50 83 51]
  [ 1  8 57 53 72 66 23]
  [42 30  9 11 25 87 24]
  [62 83  7 46 12 97 90]
  [57 63 93 18 25 70 41]
  [58 29 48 49 33 76 12]
  [50 93 17 92  5 83 47]
  [16 97

In [34]:
# 抽取每个班级第0个学生, 第5个学生和第9个学生的全部成绩
p = tf.gather(scores, [0, 5, 9], axis = 1)
print(p)

tf.Tensor(
[[[11 94 64 27 72  9 87]
  [35 75  2 72 81 14 46]
  [23 20 19 64 94 62 15]]

 [[95 63 47 19 12 70 53]
  [24 39 17 53 23 76 67]
  [68 11 86 61 73 62 75]]

 [[12 97 42 95 35 54 52]
  [77 46 17 63 98 67 37]
  [99  9 57 50 93 34 10]]

 [[61 53 30 10 29 30 93]
  [62 83  7 46 12 97 90]
  [16 97 18 67 13 60 24]]], shape=(4, 3, 7), dtype=int32)


In [36]:
# 抽取每个班级第0个学生, 第5个学生, 第9个学生的第1门课程、第3门课程、第6门课程
q = tf.gather(tf.gather(scores, [0, 5, 9], axis = 1), [1, 3, 6], axis = 2)
print(q)

tf.Tensor(
[[[94 27 87]
  [75 72 46]
  [20 64 15]]

 [[63 19 53]
  [39 53 67]
  [11 61 75]]

 [[97 95 52]
  [46 63 37]
  [ 9 50 10]]

 [[53 10 93]
  [83 46 90]
  [97 67 24]]], shape=(4, 3, 3), dtype=int32)


In [39]:
# 抽取第0个班级第0个学生, 第2个班级第4个学生, 第三个班级第6个学生的第1门课的成绩
s = tf.gather_nd(scores, indices = [(0, 0, 1), (2, 4, 1), (3, 6, 1)])
print(s)

tf.Tensor([94 11 63], shape=(3,), dtype=int32)


In [40]:
#抽取第0、5、9个学生的全部成绩
p = tf.boolean_mask(scores, [True, False, False, False, False, True, False, False, False, True], axis = 1)
print(p)

tf.Tensor(
[[[11 94 64 27 72  9 87]
  [35 75  2 72 81 14 46]
  [23 20 19 64 94 62 15]]

 [[95 63 47 19 12 70 53]
  [24 39 17 53 23 76 67]
  [68 11 86 61 73 62 75]]

 [[12 97 42 95 35 54 52]
  [77 46 17 63 98 67 37]
  [99  9 57 50 93 34 10]]

 [[61 53 30 10 29 30 93]
  [62 83  7 46 12 97 90]
  [16 97 18 67 13 60 24]]], shape=(4, 3, 7), dtype=int32)


使用tf.where和tf.scatter_nd修改张量值

In [43]:
c = tf.constant([[-1, 1, -1], [2, 2, -2], [3, -3, 3]], dtype = tf.float32)
d = tf.where(c < 0, x = tf.fill(c.shape, np.nan), y = c)  # 如果这里传入x, y。那么当条件为真就取x, 条件为假就取y
print(d)

tf.Tensor(
[[nan  1. nan]
 [ 2.  2. nan]
 [ 3. nan  3.]], shape=(3, 3), dtype=float32)


In [45]:
indices = tf.where(c < 0)
print(indices)

tf.Tensor(
[[0 0]
 [0 2]
 [1 2]
 [2 1]], shape=(4, 2), dtype=int64)


In [47]:
# 将张量的第[0,0]和[2,1]两个位置的元素替换为0得到新的张量
d = c - tf.scatter_nd([[0, 0], [2, 1]], [c[0, 0], c[2, 1]], c.shape)  # scatter_nd是0初始化的
print(d)

tf.Tensor(
[[ 0.  1. -1.]
 [ 2.  2. -2.]
 [ 3.  0.  3.]], shape=(3, 3), dtype=float32)


## 3 维度变换

维度变换的函数主要有：
* tf.reshape: 可以迅速改变张量形状而不会真的改变储存顺序, 所以该操作十分迅速并且可逆
* tf.squeeze: 减少维度
* tf.expand_dims: 可以增加维度
* tf.transpose: 可以交换维度

In [54]:
a = tf.Variable(tf.random.uniform(shape = [1,3,3,2], minval = 0, maxval = 255, dtype = tf.int32))
print(a.shape)
print(a)

(1, 3, 3, 2)
<tf.Variable 'Variable:0' shape=(1, 3, 3, 2) dtype=int32, numpy=
array([[[[148,  43],
         [184,  17],
         [ 78, 224]],

        [[223, 128],
         [168, 144],
         [168, 147]],

        [[133,  36],
         [178,   4],
         [ 86, 244]]]], dtype=int32)>


In [56]:
b = tf.reshape(a, [3, 6])  # 值拷贝
print(b)
a.assign_sub(a)
print(a)
print(b)
a = tf.random.uniform(shape = [1,3,3,2], minval = 0, maxval = 255, dtype = tf.int32)
print(a)

tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]], shape=(3, 6), dtype=int32)
<tf.Variable 'Variable:0' shape=(1, 3, 3, 2) dtype=int32, numpy=
array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]], dtype=int32)>
tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]], shape=(3, 6), dtype=int32)
tf.Tensor(
[[[[216  96]
   [188 215]
   [212 194]]

  [[ 72 124]
   [ 68 224]
   [212 180]]

  [[ 18 231]
   [  4  47]
   [123 231]]]], shape=(1, 3, 3, 2), dtype=int32)


In [57]:
s = tf.squeeze(a)  # 消除1的维度
print(s)

tf.Tensor(
[[[216  96]
  [188 215]
  [212 194]]

 [[ 72 124]
  [ 68 224]
  [212 180]]

 [[ 18 231]
  [  4  47]
  [123 231]]], shape=(3, 3, 2), dtype=int32)


In [59]:
d = tf.expand_dims(s, axis = 0)  # 在第一个轴上添加一个维度, 
print(d)

tf.Tensor(
[[[[216  96]
   [188 215]
   [212 194]]

  [[ 72 124]
   [ 68 224]
   [212 180]]

  [[ 18 231]
   [  4  47]
   [123 231]]]], shape=(1, 3, 3, 2), dtype=int32)


In [72]:
### Batch, Height, Width, Channel
a = tf.random.uniform(shape = [10, 6, 5, 4], minval = 0, maxval = 255, dtype = tf.int32)
print(a.shape)

# 把Channel end转为Channel first
s = tf.transpose(a, perm = [0, 3, 2, 1])
print(s.shape)

(10, 6, 5, 4)
(10, 4, 5, 6)


## 4 合并分割
可以使用tf.concat和tf.stack对多个张量进行合并, 可以用tf.split把一个张量分割成多个张量

tf.concat和tf.stack有略微的区别, 前者是连接不会增加维度, 后者是堆叠会增加维度

In [79]:
a = tf.constant([[1.0, 2], [3, 4]])
b = tf.constant([[5.0, 6], [7, 8]])
c = tf.constant([[9.0, 10], [11, 12]])
d = tf.concat([a, b, c], axis = 0)
print(d)

tf.Tensor(
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]], shape=(6, 2), dtype=float32)


In [76]:
print(tf.stack([a, b, c], axis = 0))

tf.Tensor(
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]], shape=(3, 2, 2), dtype=float32)


In [77]:
print(tf.stack([a, b, c], axis = 1))

tf.Tensor(
[[[ 1.  2.]
  [ 5.  6.]
  [ 9. 10.]]

 [[ 3.  4.]
  [ 7.  8.]
  [11. 12.]]], shape=(2, 3, 2), dtype=float32)


In [80]:
# tf.split是tf.concat的逆运算
print(tf.split(d, 3, axis = 0))  # 分割成list

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 9., 10.],
       [11., 12.]], dtype=float32)>]


In [81]:
print(tf.split(d, [1, 2, 3], axis = 0))

[<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [5., 6.]], dtype=float32)>, <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>]
